name: qr_project
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_svg: ^2.0.7
  get: 4.6.6
  open_file: ^3.3.2
  path_provider: ^2.1.1
  pdf: ^3.3.4
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: 2.0.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/rocket.svg
    - assets/login.svg
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins-Thin.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Black.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-ExtraBold.ttf
