// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKKghMQX-fmZKRndHEnxpmA4Wzcg5MZaM',
    appId: '1:149405810555:web:f9254eb7c8db3b7e51c7de',
    messagingSenderId: '149405810555',
    projectId: 'qr-code-sindev',
    authDomain: 'qr-code-sindev.firebaseapp.com',
    storageBucket: 'qr-code-sindev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv4X0rFSupdCWurpJQLHsI01Snk2RVOug',
    appId: '1:149405810555:android:758d3fa98f9fd37f51c7de',
    messagingSenderId: '149405810555',
    projectId: 'qr-code-sindev',
    storageBucket: 'qr-code-sindev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtb5tSuUcsmpDKhMY1NjwLIFoaL8GOovQ',
    appId: '1:149405810555:ios:2faa77881aa59a1151c7de',
    messagingSenderId: '149405810555',
    projectId: 'qr-code-sindev',
    storageBucket: 'qr-code-sindev.appspot.com',
    iosBundleId: 'com.sindev.qrProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtb5tSuUcsmpDKhMY1NjwLIFoaL8GOovQ',
    appId: '1:149405810555:ios:4964a87e0f1cf17351c7de',
    messagingSenderId: '149405810555',
    projectId: 'qr-code-sindev',
    storageBucket: 'qr-code-sindev.appspot.com',
    iosBundleId: 'com.sindev.qrProject.RunnerTests',
  );
}
